# Generated by Django 4.0.6 on 2022-07-16 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('paletra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palestras.palestra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Luta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=64, null=True)),
                ('paletra1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palestra1', to='palestras.palestra')),
                ('paletra2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palestra2', to='palestras.palestra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
