# Generated by Django 4.0.6 on 2022-07-16 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre', models.TextField()),
                ('imagem', models.URLField(max_length=1024, null=True)),
                ('github_link', models.URLField(max_length=1024, null=True)),
                ('twitter_link', models.URLField(max_length=1024, null=True)),
                ('site_link', models.URLField(max_length=1024, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
